#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatosClassLibrary
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Productos")]
	public partial class DcProductosDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertTbl_Categoria(Tbl_Categoria instance);
    partial void UpdateTbl_Categoria(Tbl_Categoria instance);
    partial void DeleteTbl_Categoria(Tbl_Categoria instance);
    partial void InsertTbl_Producto(Tbl_Producto instance);
    partial void UpdateTbl_Producto(Tbl_Producto instance);
    partial void DeleteTbl_Producto(Tbl_Producto instance);
    #endregion
		
		public DcProductosDataContext() : 
				base(global::AccesoDatosClassLibrary.Properties.Settings.Default.ProductosConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DcProductosDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DcProductosDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DcProductosDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DcProductosDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Tbl_Categoria> Tbl_Categoria
		{
			get
			{
				return this.GetTable<Tbl_Categoria>();
			}
		}
		
		public System.Data.Linq.Table<Tbl_Producto> Tbl_Producto
		{
			get
			{
				return this.GetTable<Tbl_Producto>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_Categoria")]
	public partial class Tbl_Categoria : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _cat_nombre;
		
		private short _cat_id;
		
		private string _cat_descripcion;
		
		private char _cat_status;
		
		private System.DateTime _cat_fechacreacion;
		
		private EntitySet<Tbl_Producto> _Tbl_Producto;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncat_nombreChanging(string value);
    partial void Oncat_nombreChanged();
    partial void Oncat_idChanging(short value);
    partial void Oncat_idChanged();
    partial void Oncat_descripcionChanging(string value);
    partial void Oncat_descripcionChanged();
    partial void Oncat_statusChanging(char value);
    partial void Oncat_statusChanged();
    partial void Oncat_fechacreacionChanging(System.DateTime value);
    partial void Oncat_fechacreacionChanged();
    #endregion
		
		public Tbl_Categoria()
		{
			this._Tbl_Producto = new EntitySet<Tbl_Producto>(new Action<Tbl_Producto>(this.attach_Tbl_Producto), new Action<Tbl_Producto>(this.detach_Tbl_Producto));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cat_nombre", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string cat_nombre
		{
			get
			{
				return this._cat_nombre;
			}
			set
			{
				if ((this._cat_nombre != value))
				{
					this.Oncat_nombreChanging(value);
					this.SendPropertyChanging();
					this._cat_nombre = value;
					this.SendPropertyChanged("cat_nombre");
					this.Oncat_nombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cat_id", DbType="SmallInt NOT NULL", IsPrimaryKey=true)]
		public short cat_id
		{
			get
			{
				return this._cat_id;
			}
			set
			{
				if ((this._cat_id != value))
				{
					this.Oncat_idChanging(value);
					this.SendPropertyChanging();
					this._cat_id = value;
					this.SendPropertyChanged("cat_id");
					this.Oncat_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cat_descripcion", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string cat_descripcion
		{
			get
			{
				return this._cat_descripcion;
			}
			set
			{
				if ((this._cat_descripcion != value))
				{
					this.Oncat_descripcionChanging(value);
					this.SendPropertyChanging();
					this._cat_descripcion = value;
					this.SendPropertyChanged("cat_descripcion");
					this.Oncat_descripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cat_status", DbType="Char(1) NOT NULL")]
		public char cat_status
		{
			get
			{
				return this._cat_status;
			}
			set
			{
				if ((this._cat_status != value))
				{
					this.Oncat_statusChanging(value);
					this.SendPropertyChanging();
					this._cat_status = value;
					this.SendPropertyChanged("cat_status");
					this.Oncat_statusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cat_fechacreacion", DbType="DateTime NOT NULL")]
		public System.DateTime cat_fechacreacion
		{
			get
			{
				return this._cat_fechacreacion;
			}
			set
			{
				if ((this._cat_fechacreacion != value))
				{
					this.Oncat_fechacreacionChanging(value);
					this.SendPropertyChanging();
					this._cat_fechacreacion = value;
					this.SendPropertyChanged("cat_fechacreacion");
					this.Oncat_fechacreacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_Categoria_Tbl_Producto", Storage="_Tbl_Producto", ThisKey="cat_id", OtherKey="cat_id")]
		public EntitySet<Tbl_Producto> Tbl_Producto
		{
			get
			{
				return this._Tbl_Producto;
			}
			set
			{
				this._Tbl_Producto.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Tbl_Producto(Tbl_Producto entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_Categoria = this;
		}
		
		private void detach_Tbl_Producto(Tbl_Producto entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_Categoria = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_Producto")]
	public partial class Tbl_Producto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _pro_id;
		
		private string _pro_codigo;
		
		private string _pro_nombre;
		
		private decimal _pro_preciocompra;
		
		private decimal _pro_precioventa;
		
		private string _pro_descripcion;
		
		private int _pro_stockminimo;
		
		private int _pro_stockmaximo;
		
		private System.DateTime _pro_fechacreacion;
		
		private char _pro_status;
		
		private System.Nullable<short> _cat_id;
		
		private EntityRef<Tbl_Categoria> _Tbl_Categoria;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onpro_idChanging(int value);
    partial void Onpro_idChanged();
    partial void Onpro_codigoChanging(string value);
    partial void Onpro_codigoChanged();
    partial void Onpro_nombreChanging(string value);
    partial void Onpro_nombreChanged();
    partial void Onpro_preciocompraChanging(decimal value);
    partial void Onpro_preciocompraChanged();
    partial void Onpro_precioventaChanging(decimal value);
    partial void Onpro_precioventaChanged();
    partial void Onpro_descripcionChanging(string value);
    partial void Onpro_descripcionChanged();
    partial void Onpro_stockminimoChanging(int value);
    partial void Onpro_stockminimoChanged();
    partial void Onpro_stockmaximoChanging(int value);
    partial void Onpro_stockmaximoChanged();
    partial void Onpro_fechacreacionChanging(System.DateTime value);
    partial void Onpro_fechacreacionChanged();
    partial void Onpro_statusChanging(char value);
    partial void Onpro_statusChanged();
    partial void Oncat_idChanging(System.Nullable<short> value);
    partial void Oncat_idChanged();
    #endregion
		
		public Tbl_Producto()
		{
			this._Tbl_Categoria = default(EntityRef<Tbl_Categoria>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int pro_id
		{
			get
			{
				return this._pro_id;
			}
			set
			{
				if ((this._pro_id != value))
				{
					this.Onpro_idChanging(value);
					this.SendPropertyChanging();
					this._pro_id = value;
					this.SendPropertyChanged("pro_id");
					this.Onpro_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_codigo", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string pro_codigo
		{
			get
			{
				return this._pro_codigo;
			}
			set
			{
				if ((this._pro_codigo != value))
				{
					this.Onpro_codigoChanging(value);
					this.SendPropertyChanging();
					this._pro_codigo = value;
					this.SendPropertyChanged("pro_codigo");
					this.Onpro_codigoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_nombre", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string pro_nombre
		{
			get
			{
				return this._pro_nombre;
			}
			set
			{
				if ((this._pro_nombre != value))
				{
					this.Onpro_nombreChanging(value);
					this.SendPropertyChanging();
					this._pro_nombre = value;
					this.SendPropertyChanged("pro_nombre");
					this.Onpro_nombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_preciocompra", DbType="Decimal(8,4) NOT NULL")]
		public decimal pro_preciocompra
		{
			get
			{
				return this._pro_preciocompra;
			}
			set
			{
				if ((this._pro_preciocompra != value))
				{
					this.Onpro_preciocompraChanging(value);
					this.SendPropertyChanging();
					this._pro_preciocompra = value;
					this.SendPropertyChanged("pro_preciocompra");
					this.Onpro_preciocompraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_precioventa", DbType="Decimal(8,4) NOT NULL")]
		public decimal pro_precioventa
		{
			get
			{
				return this._pro_precioventa;
			}
			set
			{
				if ((this._pro_precioventa != value))
				{
					this.Onpro_precioventaChanging(value);
					this.SendPropertyChanging();
					this._pro_precioventa = value;
					this.SendPropertyChanged("pro_precioventa");
					this.Onpro_precioventaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_descripcion", DbType="NVarChar(100)")]
		public string pro_descripcion
		{
			get
			{
				return this._pro_descripcion;
			}
			set
			{
				if ((this._pro_descripcion != value))
				{
					this.Onpro_descripcionChanging(value);
					this.SendPropertyChanging();
					this._pro_descripcion = value;
					this.SendPropertyChanged("pro_descripcion");
					this.Onpro_descripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_stockminimo", DbType="Int NOT NULL")]
		public int pro_stockminimo
		{
			get
			{
				return this._pro_stockminimo;
			}
			set
			{
				if ((this._pro_stockminimo != value))
				{
					this.Onpro_stockminimoChanging(value);
					this.SendPropertyChanging();
					this._pro_stockminimo = value;
					this.SendPropertyChanged("pro_stockminimo");
					this.Onpro_stockminimoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_stockmaximo", DbType="Int NOT NULL")]
		public int pro_stockmaximo
		{
			get
			{
				return this._pro_stockmaximo;
			}
			set
			{
				if ((this._pro_stockmaximo != value))
				{
					this.Onpro_stockmaximoChanging(value);
					this.SendPropertyChanging();
					this._pro_stockmaximo = value;
					this.SendPropertyChanged("pro_stockmaximo");
					this.Onpro_stockmaximoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_fechacreacion", DbType="DateTime NOT NULL")]
		public System.DateTime pro_fechacreacion
		{
			get
			{
				return this._pro_fechacreacion;
			}
			set
			{
				if ((this._pro_fechacreacion != value))
				{
					this.Onpro_fechacreacionChanging(value);
					this.SendPropertyChanging();
					this._pro_fechacreacion = value;
					this.SendPropertyChanged("pro_fechacreacion");
					this.Onpro_fechacreacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_status", DbType="Char(1) NOT NULL")]
		public char pro_status
		{
			get
			{
				return this._pro_status;
			}
			set
			{
				if ((this._pro_status != value))
				{
					this.Onpro_statusChanging(value);
					this.SendPropertyChanging();
					this._pro_status = value;
					this.SendPropertyChanged("pro_status");
					this.Onpro_statusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cat_id", DbType="SmallInt")]
		public System.Nullable<short> cat_id
		{
			get
			{
				return this._cat_id;
			}
			set
			{
				if ((this._cat_id != value))
				{
					if (this._Tbl_Categoria.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oncat_idChanging(value);
					this.SendPropertyChanging();
					this._cat_id = value;
					this.SendPropertyChanged("cat_id");
					this.Oncat_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_Categoria_Tbl_Producto", Storage="_Tbl_Categoria", ThisKey="cat_id", OtherKey="cat_id", IsForeignKey=true)]
		public Tbl_Categoria Tbl_Categoria
		{
			get
			{
				return this._Tbl_Categoria.Entity;
			}
			set
			{
				Tbl_Categoria previousValue = this._Tbl_Categoria.Entity;
				if (((previousValue != value) 
							|| (this._Tbl_Categoria.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tbl_Categoria.Entity = null;
						previousValue.Tbl_Producto.Remove(this);
					}
					this._Tbl_Categoria.Entity = value;
					if ((value != null))
					{
						value.Tbl_Producto.Add(this);
						this._cat_id = value.cat_id;
					}
					else
					{
						this._cat_id = default(Nullable<short>);
					}
					this.SendPropertyChanged("Tbl_Categoria");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
